name: stride
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.12.3
  shared_preferences: ^2.5.3
  timezone: ^0.10.1
  fl_chart: ^1.0.0
  intl: ^0.20.2
  provider: ^6.1.5
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
